
import { StudentRecord } from './types';

export const SAMPLE_DATA: StudentRecord[] = [
  { id: '1', name: 'Alice Johnson', age: 18, city: 'Austin', state: 'TX', schoolName: 'Westlake High', schoolType: 'High School', schoolState: 'TX', schoolCity: 'Austin', cumulativeGpa: 3.8, unweightedGpa: 3.7, weightedGpa: 4.2, rigorCoursesCount: 5, creditsEarned: 24, majorInterest: 'Biology', graduationYear: 2024 },
  { id: '2', name: 'Bob Smith', age: 19, city: 'Seattle', state: 'WA', schoolName: 'Rainier High', schoolType: 'High School', schoolState: 'WA', schoolCity: 'Seattle', cumulativeGpa: 3.2, unweightedGpa: 3.1, weightedGpa: 3.4, rigorCoursesCount: 2, creditsEarned: 20, majorInterest: 'Arts', graduationYear: 2024 },
  { id: '3', name: 'Charlie Davis', age: 17, city: 'Boston', state: 'MA', schoolName: 'Beacon Academy', schoolType: 'High School', schoolState: 'MA', schoolCity: 'Boston', cumulativeGpa: 4.0, unweightedGpa: 3.9, weightedGpa: 4.5, rigorCoursesCount: 8, creditsEarned: 28, majorInterest: 'Computer Science', graduationYear: 2025 },
  { id: '4', name: 'Diana Prince', age: 18, city: 'New York', state: 'NY', schoolName: 'Empire Prep', schoolType: 'High School', schoolState: 'NY', schoolCity: 'New York', cumulativeGpa: 3.6, unweightedGpa: 3.5, weightedGpa: 3.9, rigorCoursesCount: 4, creditsEarned: 22, majorInterest: 'History', graduationYear: 2024 },
  { id: '5', name: 'Ethan Hunt', age: 20, city: 'Los Angeles', state: 'CA', schoolName: 'Pacific College', schoolType: 'College', schoolState: 'CA', schoolCity: 'Santa Monica', cumulativeGpa: 3.5, unweightedGpa: 3.4, weightedGpa: 3.5, rigorCoursesCount: 10, creditsEarned: 60, majorInterest: 'Engineering', graduationYear: 2026 },
  { id: '6', name: 'Fiona Gallagher', age: 18, city: 'Chicago', state: 'IL', schoolName: 'Southside High', schoolType: 'High School', schoolState: 'IL', schoolCity: 'Chicago', cumulativeGpa: 2.9, unweightedGpa: 2.8, weightedGpa: 3.1, rigorCoursesCount: 1, creditsEarned: 18, majorInterest: 'Nursing', graduationYear: 2024 },
  { id: '7', name: 'George Miller', age: 19, city: 'Austin', state: 'TX', schoolName: 'Austin High', schoolType: 'High School', schoolState: 'TX', schoolCity: 'Austin', cumulativeGpa: 3.4, unweightedGpa: 3.3, weightedGpa: 3.7, rigorCoursesCount: 3, creditsEarned: 21, majorInterest: 'Business', graduationYear: 2024 },
  { id: '8', name: 'Hannah Abbott', age: 17, city: 'London', state: 'OH', schoolName: 'Huron High', schoolType: 'High School', schoolState: 'OH', schoolCity: 'London', cumulativeGpa: 3.9, unweightedGpa: 3.8, weightedGpa: 4.3, rigorCoursesCount: 6, creditsEarned: 25, majorInterest: 'English', graduationYear: 2025 },
  { id: '9', name: 'Ian Wright', age: 18, city: 'Miami', state: 'FL', schoolName: 'Biscayne Prep', schoolType: 'High School', schoolState: 'FL', schoolCity: 'Miami', cumulativeGpa: 3.1, unweightedGpa: 3.0, weightedGpa: 3.2, rigorCoursesCount: 2, creditsEarned: 19, majorInterest: 'Sports Management', graduationYear: 2024 },
  { id: '10', name: 'Jane Doe', age: 19, city: 'Seattle', state: 'WA', schoolName: 'Emerald City High', schoolType: 'High School', schoolState: 'WA', schoolCity: 'Seattle', cumulativeGpa: 3.75, unweightedGpa: 3.6, weightedGpa: 4.1, rigorCoursesCount: 5, creditsEarned: 23, majorInterest: 'Physics', graduationYear: 2024 },
  { id: '11', name: 'Kevin Hart', age: 20, city: 'Philadelphia', state: 'PA', schoolName: 'Philly College', schoolType: 'College', schoolState: 'PA', schoolCity: 'Philadelphia', cumulativeGpa: 3.3, unweightedGpa: 3.2, weightedGpa: 3.3, rigorCoursesCount: 7, creditsEarned: 45, majorInterest: 'Communication', graduationYear: 2026 },
  { id: '12', name: 'Laura Palmer', age: 18, city: 'Twin Peaks', state: 'WA', schoolName: 'Twin Peaks High', schoolType: 'High School', schoolState: 'WA', schoolCity: 'Twin Peaks', cumulativeGpa: 3.95, unweightedGpa: 3.9, weightedGpa: 4.6, rigorCoursesCount: 9, creditsEarned: 30, majorInterest: 'Psychology', graduationYear: 2024 },
  { id: '13', name: 'Michael Scott', age: 18, city: 'Scranton', state: 'PA', schoolName: 'Scranton High', schoolType: 'High School', schoolState: 'PA', schoolCity: 'Scranton', cumulativeGpa: 2.5, unweightedGpa: 2.4, weightedGpa: 2.7, rigorCoursesCount: 0, creditsEarned: 15, majorInterest: 'Management', graduationYear: 2024 },
  { id: '14', name: 'Pam Beesly', age: 18, city: 'Scranton', state: 'PA', schoolName: 'Scranton High', schoolType: 'High School', schoolState: 'PA', schoolCity: 'Scranton', cumulativeGpa: 3.6, unweightedGpa: 3.5, weightedGpa: 3.8, rigorCoursesCount: 3, creditsEarned: 22, majorInterest: 'Art History', graduationYear: 2024 },
  { id: '15', name: 'Jim Halpert', age: 19, city: 'Scranton', state: 'PA', schoolName: 'Scranton High', schoolType: 'High School', schoolState: 'PA', schoolCity: 'Scranton', cumulativeGpa: 3.3, unweightedGpa: 3.2, weightedGpa: 3.5, rigorCoursesCount: 2, creditsEarned: 20, majorInterest: 'Marketing', graduationYear: 2024 },
  { id: '16', name: 'Dwight Schrute', age: 18, city: 'Scranton', state: 'PA', schoolName: 'Lackawanna High', schoolType: 'High School', schoolState: 'PA', schoolCity: 'Scranton', cumulativeGpa: 4.0, unweightedGpa: 4.0, weightedGpa: 5.0, rigorCoursesCount: 12, creditsEarned: 32, majorInterest: 'Agriculture', graduationYear: 2024 },
  { id: '17', name: 'Angela Martin', age: 17, city: 'Scranton', state: 'PA', schoolName: 'Lackawanna High', schoolType: 'High School', schoolState: 'PA', schoolCity: 'Scranton', cumulativeGpa: 3.9, unweightedGpa: 3.8, weightedGpa: 4.2, rigorCoursesCount: 6, creditsEarned: 26, majorInterest: 'Accounting', graduationYear: 2025 },
  { id: '18', name: 'Oscar Martinez', age: 18, city: 'Scranton', state: 'PA', schoolName: 'Scranton High', schoolType: 'High School', schoolState: 'PA', schoolCity: 'Scranton', cumulativeGpa: 3.95, unweightedGpa: 3.9, weightedGpa: 4.8, rigorCoursesCount: 10, creditsEarned: 30, majorInterest: 'Economics', graduationYear: 2024 },
  { id: '19', name: 'Kevin Malone', age: 19, city: 'Scranton', state: 'PA', schoolName: 'Scranton High', schoolType: 'High School', schoolState: 'PA', schoolCity: 'Scranton', cumulativeGpa: 2.1, unweightedGpa: 2.0, weightedGpa: 2.2, rigorCoursesCount: 0, creditsEarned: 12, majorInterest: 'Culinary Arts', graduationYear: 2024 },
  { id: '20', name: 'Stanley Hudson', age: 21, city: 'Chicago', state: 'IL', schoolName: 'Windy City College', schoolType: 'College', schoolState: 'IL', schoolCity: 'Chicago', cumulativeGpa: 3.0, unweightedGpa: 3.0, weightedGpa: 3.0, rigorCoursesCount: 4, creditsEarned: 90, majorInterest: 'Retirement Planning', graduationYear: 2025 },
];

export const DEMO_API_DATA: StudentRecord[] = [
  { id: '101', name: 'Marie Curie', age: 20, city: 'Warsaw', state: 'PL', schoolName: 'Sorbonne University', schoolType: 'College', schoolState: 'FR', schoolCity: 'Paris', cumulativeGpa: 4.0, unweightedGpa: 4.0, weightedGpa: 4.0, rigorCoursesCount: 15, creditsEarned: 120, majorInterest: 'Radiology', graduationYear: 2024 },
  { id: '102', name: 'Albert Einstein', age: 19, city: 'Ulm', state: 'DE', schoolName: 'Zurich Polytechnic', schoolType: 'College', schoolState: 'CH', schoolCity: 'Zurich', cumulativeGpa: 3.9, unweightedGpa: 3.8, weightedGpa: 3.9, rigorCoursesCount: 12, creditsEarned: 90, majorInterest: 'Theoretical Physics', graduationYear: 2025 },
  { id: '103', name: 'Ada Lovelace', age: 18, city: 'London', state: 'UK', schoolName: 'University of London', schoolType: 'College', schoolState: 'UK', schoolCity: 'London', cumulativeGpa: 4.0, unweightedGpa: 4.0, weightedGpa: 4.0, rigorCoursesCount: 10, creditsEarned: 60, majorInterest: 'Mathematics', graduationYear: 2026 },
  { id: '104', name: 'Isaac Newton', age: 21, city: 'Woolsthorpe', state: 'UK', schoolName: 'Trinity College', schoolType: 'College', schoolState: 'UK', schoolCity: 'Cambridge', cumulativeGpa: 3.8, unweightedGpa: 3.7, weightedGpa: 3.8, rigorCoursesCount: 14, creditsEarned: 110, majorInterest: 'Physics', graduationYear: 2024 },
  { id: '105', name: 'Nikola Tesla', age: 22, city: 'Smiljan', state: 'HR', schoolName: 'Graz University of Technology', schoolType: 'College', schoolState: 'AT', schoolCity: 'Graz', cumulativeGpa: 4.0, unweightedGpa: 3.9, weightedGpa: 4.0, rigorCoursesCount: 15, creditsEarned: 130, majorInterest: 'Electrical Engineering', graduationYear: 2024 },
  { id: '106', name: 'Charles Darwin', age: 20, city: 'Shrewsbury', state: 'UK', schoolName: 'Christ\'s College', schoolType: 'College', schoolState: 'UK', schoolCity: 'Cambridge', cumulativeGpa: 3.1, unweightedGpa: 3.0, weightedGpa: 3.1, rigorCoursesCount: 5, creditsEarned: 95, majorInterest: 'Natural History', graduationYear: 2025 },
  { id: '107', name: 'Rosalind Franklin', age: 19, city: 'London', state: 'UK', schoolName: 'Newnham College', schoolType: 'College', schoolState: 'UK', schoolCity: 'Cambridge', cumulativeGpa: 3.95, unweightedGpa: 3.9, weightedGpa: 3.95, rigorCoursesCount: 13, creditsEarned: 75, majorInterest: 'Chemistry', graduationYear: 2026 },
  { id: '108', name: 'Stephen Hawking', age: 21, city: 'Oxford', state: 'UK', schoolName: 'University of Cambridge', schoolType: 'College', schoolState: 'UK', schoolCity: 'Cambridge', cumulativeGpa: 4.0, unweightedGpa: 4.0, weightedGpa: 4.0, rigorCoursesCount: 15, creditsEarned: 105, majorInterest: 'Cosmology', graduationYear: 2025 },
  { id: '109', name: 'Katherine Johnson', age: 18, city: 'White Sulphur Springs', state: 'WV', schoolName: 'West Virginia State', schoolType: 'College', schoolState: 'WV', schoolCity: 'Institute', cumulativeGpa: 4.0, unweightedGpa: 4.0, weightedGpa: 4.0, rigorCoursesCount: 15, creditsEarned: 120, majorInterest: 'Mathematics', graduationYear: 2024 },
  { id: '110', name: 'Alan Turing', age: 20, city: 'London', state: 'UK', schoolName: 'King\'s College', schoolType: 'College', schoolState: 'UK', schoolCity: 'Cambridge', cumulativeGpa: 4.0, unweightedGpa: 4.0, weightedGpa: 4.0, rigorCoursesCount: 15, creditsEarned: 85, majorInterest: 'Computer Science', graduationYear: 2026 },
];
